### ISSUE TITLE
Package manager support

### ISSUE THREAD

**Issue by zynth666** [theproductiveprogrammer/flipbook-viewer#2]
Hello,

is there an option to install via npm? Or how are you supposed to install it? Just download manually?

**Comment by theproductiveprogrammer** [comment]
Hi @zynth666

Yes it's available on npm: https://www.npmjs.com/package/flipbook-viewer , installable in the usual way with

```sh
$ npm install flipbook-viewer
```

I hope that helps. Apologies for the delayed reply. Was on holiday.

**Comment by Numerizen** [comment]
Shouldn't it be : 

`$ npm install flipbook-viewer`

... ?

**Comment by theproductiveprogrammer** [comment]
Whoops - yes you're right. Corrected. Thanks.
