### ISSUE TITLE
maximum dimensions

### ISSUE THREAD

**Issue by brianteeman** [theproductiveprogrammer/flipbook-viewer#3]
Hi, great project. 

Maybe I missed something obvious but I couldn't see a way to set the flipbook to use the maximum height and width of the viewport. I could only see a way to se absolute dimensions in pixels.

**Comment by theproductiveprogrammer** [comment]
Hi @brianteeman 

Thanks for the appreciation! ❤️ 

To set the flipbook to the height and width of the window's client area (the viewport) would look something like:

```is
const opts = {
  width: window.innerWidth,
  height: window.innerHeight,
}

flipbook(book, 'div-id', opts, (err, viewer) => ...
```

I hope that helps. Apologies for the late response. Was on holiday.

**Comment by brianteeman** [comment]
thanks
