### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by TobiasKrais** [theproductiveprogrammer/flipbook-viewer#4]
I'm trying hard to get the demo working. Here my page with just the repo code inside: https://flip.design-to-use.de/test/test-pdf.html

1.  I had to fix https://github.com/theproductiveprogrammer/flipbook-viewer/blob/750eea07e237a3ccd5a2dee714bafde64ae7078f/test/test-pdf.html#L12 to `<script src="./test-pdf.js"></script>`, because the file was not found.
2.  I had to fix the same line to `<script type="module" src="/test-pdf.js"></script>`, because  I had a browser error "Uncaught SyntaxError: import declarations may only appear at top level of a module".

Now I have a next error on my browser console: Uncaught TypeError: The specifier "@tpp/htm-x" was a bare specifier but was not remapped to anything. Relative module specifiers must begin with "./", "../" or "/". How to solve?

**Comment by theproductiveprogrammer** [comment]
Hi @TobiasKrais,

From what I understand you are trying to do, the best way would be to use a javascript bundler like [Webpack](https://webpack.js.org/).

Steps you can follow:
1. Create a webpack project similar to [this example](https://webpack.js.org/guides/getting-started/).
2. Install `flipbook-viewer` using `$ npm install flipbook-viewer`.
3. Copy the sample code from the test directory [test/pdfjs-init.js](https://github.com/theproductiveprogrammer/flipbook-viewer/blob/master/test/pdfjs-init.js), [test/book-pdf.js](https://github.com/theproductiveprogrammer/flipbook-viewer/blob/master/test/book-pdf.js), and [test/test-pdf.js](https://github.com/theproductiveprogrammer/flipbook-viewer/blob/master/test/test-pdf.js).
4. Include the `test-pdf.js` in your html. Use the [`webpack-dev-server`](https://webpack.js.org/configuration/dev-server/) or equivalent to debug/test then build the final output and include that into your production code.

Hope this helps.

**Comment by TobiasKrais** [comment]
Thank you! I will try to learn it.

**Comment by TobiasKrais** [comment]
Hi @theproductiveprogrammer,
sorry for disturbing. I succeded building the `flipbook-viewer.js` and `pdf.worker.js`. I did it this way:
```
npm init -y
npm i flipbook-viewer
npm i @tpp/htm-x
npm i events

```
Then I copied the `/src/` folder and `package-lock.json`, `package.json` and `webpack.config.js` in the folder an finally run:

`npm run && webpack build --env production`

The built succeded.

Can you please give me a hint or a example website how to integrate and use the JS files?
