### ISSUE TITLE
Is there a live demo anywhere

### ISSUE THREAD

**Issue by a4992214** [theproductiveprogrammer/flipbook-viewer#8]
Is there anywhere to see this library running with a live demo that can be seen with different types of devices?

**Comment by theproductiveprogrammer** [comment]
Hi @a4992214 ! I don't have a live demo set up anywhere but it wouldn't be hard to do. I'll try and get something up by the weekend.

**Comment by a4992214** [comment]
Hi tpp... did you get a chance to set this up?

**Comment by theproductiveprogrammer** [comment]
Hi - set it up here. It's a low budget server but should be adequate for a rough demo.

https://flipbook-viewer.charleslobo.com/
